REactivate SBT settings (Automatize Scala.js deployment (run fastOpsJS) , using https://github.com/vmunier/play-with-scalajs-example)
Now Scala.js is automatically compiled & deployed.

TODO: still error when development tools are used on Chromium:
java.lang.NoSuchMethodError: views.html.defaultpages.devNotFound_Scope0$devNotFound._display_(Ljava/lang/Object;Lscala/reflect/Manifest;)Lplay/twirl/api/Appendable;]]
due to GET /assets/rdfviewer/md5.min.js.map , /assets/rdfviewer/md5.min.js.map , etc

after commits:
- ffa085c51c9839decaa04e3fa6ff75943effed0e : FIXES play.api.UnexpectedException:
    Unexpected exception[RuntimeException: java.lang.NoSuchMethodError: views.html.helper.inputText_Scope0$inputText._display_(Ljava/lang/Object;Lscala/reflect/Manifest;

- bc27a198414c31e404a8a352b48d54c02bdefc99 :

08:54:14.724 [application-akka.actor.default-dispatcher-4] ERROR application -

! @7510p0h5c - Internal server error, for (GET) [/assets/rdfviewer/md5.min.js.map] ->

play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: java.lang.NoSuchMethodError: views.html.defaultpages.devNotFound_Scope0$devNotFound._display_(Ljava/lang/Object;Lscala/reflect/Manifest;)Lplay/twirl/api/Appendable;]]