Deactivate SBT settings after commit ffa085c51c9839decaa04e3fa6ff75943effed0e : FIXES play.api.UnexpectedException:
Unexpected exception[RuntimeException: java.lang.NoSuchMethodError: views.html.helper.inputText_Scope0$inputText._display_(Ljava/lang/Object;Lscala/reflect/Manifest;)Lplay/twirl/api/Appendable;]
in http://localhost:9000/login